In [78]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer, load_digits
import math
import collections
from tabulate import tabulate

In [79]:
"""X, y = load_breast_cancer(return_X_y=True)

valores1 = []
resultados = []

pYes = 0
pNo = 0 

for i in range(len(X)):
    for j in range(len(X[0])):
        if X[i][0] not in valores1:
            valores1.append(X[i][0])

print(valores1)

print(X[0])


def probabilities(y):

    total = 0
    totalYes = 0
    totalNo = 0

    for i in y:
        if i == 0:
            totalNo += 1
        if i == 1:
            totalYes += 1
        total += 1

    pYes = totalYes/total
    pNo = totalNo/total

    probabilities = [pYes, pNo]
    return probabilities

print(probabilities(y))"""

'X, y = load_breast_cancer(return_X_y=True)\n\nvalores1 = []\nresultados = []\n\npYes = 0\npNo = 0 \n\nfor i in range(len(X)):\n    for j in range(len(X[0])):\n        if X[i][0] not in valores1:\n            valores1.append(X[i][0])\n\nprint(valores1)\n\nprint(X[0])\n\n\ndef probabilities(y):\n\n    total = 0\n    totalYes = 0\n    totalNo = 0\n\n    for i in y:\n        if i == 0:\n            totalNo += 1\n        if i == 1:\n            totalYes += 1\n        total += 1\n\n    pYes = totalYes/total\n    pNo = totalNo/total\n\n    probabilities = [pYes, pNo]\n    return probabilities\n\nprint(probabilities(y))'

In [ ]:
"""X, y = load_digits(return_X_y=True)

valores1 = []
resultados = []

pYes = 0
pNo = 0

for i in range(len(X)):
    for j in range(len(X[0])):
        if X[i][0] not in valores1:
            valores1.append(X[i][0])

print(valores1)

print(X[0])


def probabilities(x, y):

    classes = []
    resultados = []
    total = 0

    for i in y:
        if i not in classes:
            classes.append(i)

    for i in y:
        total += 1

    print(classes)

print(probabilities(X, y))

db=load_digits()

print(tabulate(X, headers=db.feature_names, tablefmt="fancy_grid"))"""


In [81]:
X, y = load_digits(return_X_y=True)

# transferindo valores do load para variaveis para depois transformar em uma funcao

data = X
labels = y

# num_linhas = quantidade de instancias
# num_colunas = quantidade deatributos por instancia

num_linhas = len(data)
num_colunas = len(data[0])

# Colocando todos os possiveis resultados em uma matriz
numLabels = []
for i in labels:
    if i not in numLabels:
        numLabels.append(i)

numLabels.sort()

# criando um vetor onde o indice no numLabels eh o mesmo da probabilidade

pLabels = [0] * len(numLabels)

i = 0
j = 0

#dando outro nome para a variavel para utilizar mais tarde
totalLabels = num_linhas

# calculando a probabilidade por resultado e guardando no vetor
for i in range(len(numLabels)):
    sum = 0
    for j in labels:
        if j == numLabels[i]:
            sum += 1
    pLabels[i] = sum/totalLabels

#salvando todos os possiveis valores para os atributos em um vetor

numData = []

for i in range(len(data)):
    for j in range(len(data[0])):
        if data[i][j] not in numData:
            numData.append(data[i][j])


numData.sort()

# criando uma matriz "matrizSoma" em que as dimensoes representam: (resultados X numero de atributos X numero de valores para os atributos)

matrizSoma = np.zeros((len(numLabels), num_colunas, len(numData)), dtype= float)
pData = np.zeros((num_colunas, len(numData), len(numLabels)), dtype= float)

print(f"linhas: {len(pData)}, colunas: {len(pData[0])},profundidade: {len(pData[0][0])}")

print(numData)
print(numLabels)

database = np.hstack((data, labels.reshape(-1, 1)))

print(f'database linhas: {len(database)}, database colunas: {len(database[0])}')

# Realizando a soma dos valores por posicao, tipo de tom e resultado

for label in range(len(numLabels)):
    vetsoma = [[0] * len(numData) for n in range(num_colunas)]
    for databaseColuna in range(len(database[label]) -1):
        for databaseLinha in range(len(database)):
            for tom in range(len(numData)):
                if database[databaseLinha][-1] == numLabels[label]:
                    vetsoma[databaseColuna][tom] += 1
        matrizSoma[label] = vetsoma

print(matrizSoma)

#print(f'linhas: {len(vetsoma)}, colunas: {len(vetsoma[0])}')

# ERRADO MAS JÁ É UM PROGRESSO


linhas: 64, colunas: 17,profundidade: 10
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
database linhas: 1797, database colunas: 65
[[[178. 178. 178. ... 178. 178. 178.]
  [178. 178. 178. ... 178. 178. 178.]
  [178. 178. 178. ... 178. 178. 178.]
  ...
  [178. 178. 178. ... 178. 178. 178.]
  [178. 178. 178. ... 178. 178. 178.]
  [178. 178. 178. ... 178. 178. 178.]]

 [[182. 182. 182. ... 182. 182. 182.]
  [182. 182. 182. ... 182. 182. 182.]
  [182. 182. 182. ... 182. 182. 182.]
  ...
  [182. 182. 182. ... 182. 182. 182.]
  [182. 182. 182. ... 182. 182. 182.]
  [182. 182. 182. ... 182. 182. 182.]]

 [[177. 177. 177. ... 177. 177. 177.]
  [177. 177. 177. ... 177. 177. 177.]
  [177. 177. 177. ... 177. 177. 177.]
  ...
  [177. 177. 177. ... 177. 177. 177.]
  [177. 177. 177. ... 177. 177. 177.]
  [177. 177. 177. ... 177. 177. 177.]]

 ...

 [[179. 179. 179. ... 179. 179. 179.]
  [179. 179. 179. ... 179. 179. 179.]
 